Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.hostname = "debian-based-server"
   
  # Customize the VM
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
    vb.name = "debian-based-server"
  end

  # Set up private network with IP
  config.vm.network "private_network", ip: "192.168.56.2"

  # Forward ports from guest to host
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 15000, host: 5000
  config.vm.network "forwarded_port", guest: 2222, host: 2323
  config.vm.network "forwarded_port", guest: 7000, host: 7000

end
