version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - /etc/ssl:/etc/ssl
      - ./nginx.conf:/etc/nginx/conf.d/default
    ports:
      - "80:80"
      - "443:443"
    networks:
      - flask_network
  flask:
    image: maarsupilami/webapp:3.0
    ports:
      - "5000:5000"
    networks:
      - flask_network

networks:
  flask_network:
