---
- name: Install apt-transport-https
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  loop:
    - ca-certificates
    - curl
    - gnupg

- name: Add official GPG key of Docker
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: Add repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Install Docker
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker
    - docker.io
    - docker-compose
    - docker-registry

- name: Log in to Docker registry
  community.general.docker_login:
    username: "{{ docker_registry_username }}"
    password: "{{ docker_registry_password }}"
    registry_url: "{{ docker_registry_url }}"

- name: Run container from registry
  community.general.docker_container:
    name: flask-app
    ports: "15000:5000"
    image: "maarsupilami/simple-webapp:2.0"
    state: present

- name: Create systemd unit file for container
  ansible.builtin.template:
    src: flask-app.service.j2
    dest: /etc/systemd/system/{{ container_name }}.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd to load new unit file
  systemd:
    daemon_reload: true

- name: Enable and start container service
  systemd:
    name: "{{ container_name }}.service"
    state: started
    enabled: true
    
