- name: Close all ports, but open necessary!
  hosts: your_host
  become: true
  tasks:
    - name: Drop all incoming traffic
      community.general.iptables:
        chain: INPUT
        jump: DROP

    - name: Configure iptables rules
      community.general.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        jump: ACCEPT
      loop:
        - 80
        - 2222
        - 15000