- name: Configurate Debian 11 server
  hosts: all
  become: true
  vars_files: ./password.yml
  tasks:
    - name: Create user
      user:
        name: "maarsu"
        shell: /bin/bash
        password: "{{ maarsu_password | password_hash('sha512')}}"
        groups: sudo
        append: yes
        create_home: true
        state: present
    - name: Update all apt packages
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes
    - name: Install sudo
      apt:
        name: sudo
        state: present
    - name: Install Midnight Commander
      apt:
       name: mc
       state: present
    - name: Install htop
      apt:
       name: htop
       state: present
    - name: Install openjdk 11
      apt:
        name: openjdk-11-jdk
        state: present
    - name: Create udemx user
      user:
        name: udemx
        shell: /bin/bash
        password: "{{ udemx_password | password_hash('sha512')}}"
        home: /opt/udemx
        create_home: true
        state: present
    - name: Change the ssh port
      shell: sed -i 's/^#Port 22/Port 2222/' /etc/ssh/sshd_config
    - name: Install nginx
      apt:
       name: nginx
       state: present
    - name: Restart service nginx, in all cases
      ansible.builtin.service:
        name: nginx
        state: restarted
    - name: Install mariaDB
      apt:
        name: mariadb-server
        state: present
    - name: Install iptables
      apt:
        name: iptables
        state: present
    
    - name: Install apt-transport-https
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
        state: latest
        update_cache: true

    - name: Add signing key
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present

    - name: Add repository into sources list
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker
          - docker.io
          - docker-compose
          - docker-registry
        state: latest

    - name: Log in to Docker registry
      community.general.docker_login:
        username: "{{ docker_registry_username }}"
        password: "{{ docker_registry_password }}"
        registry_url: "{{ docker_registry_url }}"
    - name: Run container from registry
      community.general.docker_container:
        name: flask-app
        ports: "15000:8080"
        image: "maarsupilami/webapp:3.0"
        state: started